services:
  db:
    image: postgres:16
    container_name: scotlandyard_db
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: game
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: scotlandyard_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
